@startuml
left to right direction
class users << (T,#ADD1B2) >>{
    id
    --
    email : string
    --
    password : string
    --
    name : string
    --
    created_at : timestamp
    --
    updated_at : timestamp
}
class posts << (T,#ADD1B2) >>{
    id
    --
    users_id : int
    --
    content : string
    --
    created_at : timestamp
    --
    updated_at : timestamp
}
users::id “1” -- “*" posts::users_id

class questions << (T,#ADD1B2) >>{
    id
    --
    description : string
    --
    users_id : int
    --
    created_at : timestamp
    --
    updated_at : timestamp
}
users::id “1” -- “*" questions::users_id

class question_tag << (T,#ADD1B2) >>{
    id
    --
    question_id : int
    --
    tag_id : int
    --
    created_at : timestamp
    --
    updated_at : timestamp
}
questions::id “1” -- “*" question_tag::question_id

class tag << (T,#ADD1B2) >>{
    id
    --
    name : string
    --
    created_at : timestamp
    --
    updated_at : timestamp
}
question_tag::tag_id “1” -- “1" tag::id

class question_category << (T,#ADD1B2) >>{
    id
    --
    question_id : int
    --
    category_id : int
    --
    created_at : timestamp
    --
    updated_at : timestamp
}
questions::id “1” -- “*" question_category::question_id


class category << (T,#ADD1B2) >>{
    id
    --
    name : string
    --
    parent_id : int
    --
    created_at : timestamp
    --
    updated_at : timestamp
}
question_category::category_id “1” -- “1" category::id
@enduml
